// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVkozid6-YjAXcaPHzDPXz1k8vL9U7Z74',
    appId: '1:33506779922:web:229a71402e7629fb8c09cb',
    messagingSenderId: '33506779922',
    projectId: 'entrecom-f6c44',
    authDomain: 'entrecom-f6c44.firebaseapp.com',
    storageBucket: 'entrecom-f6c44.appspot.com',
    measurementId: 'G-45DX6ZKPVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdk-7OOGtEIXPkxxw2nDkJlG0Xoqa1-l4',
    appId: '1:33506779922:android:c3b1d9dd612ce8ea8c09cb',
    messagingSenderId: '33506779922',
    projectId: 'entrecom-f6c44',
    storageBucket: 'entrecom-f6c44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVusr0yCKxuKnsR1C5y5yPa_tRmSIcWDo',
    appId: '1:33506779922:ios:95c83899530404528c09cb',
    messagingSenderId: '33506779922',
    projectId: 'entrecom-f6c44',
    storageBucket: 'entrecom-f6c44.appspot.com',
    iosClientId: '33506779922-bqmnaeg6ovsb9tr60pegj39tuv1k1091.apps.googleusercontent.com',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVusr0yCKxuKnsR1C5y5yPa_tRmSIcWDo',
    appId: '1:33506779922:ios:95c83899530404528c09cb',
    messagingSenderId: '33506779922',
    projectId: 'entrecom-f6c44',
    storageBucket: 'entrecom-f6c44.appspot.com',
    iosClientId: '33506779922-bqmnaeg6ovsb9tr60pegj39tuv1k1091.apps.googleusercontent.com',
    iosBundleId: 'com.example.application',
  );
}
